<Project>
  <PropertyGroup>
    <ModRepoRoot>$(MSBuildThisFileDirectory)</ModRepoRoot>
    <ModKitRoot Condition="'$(ModKitRoot)' == ''">$(RIMWORLD_MODKIT)</ModKitRoot>
    <ModKitRoot Condition="'$(ModKitRoot)' == ''">$(MSBuildThisFileDirectory)..\_ModKit</ModKitRoot>
    <ModKitRoot>$([MSBuild]::EnsureTrailingSlash('$(ModKitRoot)'))</ModKitRoot>
    <ModKitProps>$(ModKitRoot)RimWorldMod.props</ModKitProps>
    <ModKitMissing Condition="!Exists('$(ModKitProps)')">true</ModKitMissing>
    <TargetFramework Condition="'$(ModKitMissing)' == 'true'">net472</TargetFramework>
  </PropertyGroup>

  <Import Project="$(ModKitProps)" Condition="'$(ModKitMissing)' != 'true'" />
</Project>

